# Generated by Django 3.1.7 on 2021-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200, null=True)),
                ('date_donated', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(max_length=200, null=True)),
                ('type_of_donation', models.CharField(max_length=200, null=True)),
                ('entity', models.CharField(max_length=200, null=True)),
                ('pdf_receipt', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
