# Generated by Django 3.1.7 on 2021-05-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date_donated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pdf_receipt',
            field=models.FilePathField(null=True, path='/pdf'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('postal_address', models.TextField()),
                ('details', models.TextField()),
                ('tags', models.ManyToManyField(related_name='contacts', to='dm_page.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dm_page.contact'),
        ),
    ]
