# Generated by Django 3.1.7 on 2021-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0003_remove_donation_pdf_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='contacts', to='dm_page.Tag'),
        ),
    ]
