# Generated by Django 3.1.7 on 2021-05-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0004_auto_20210525_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donation',
            name='entity',
            field=models.CharField(choices=[('CBM', 'CBM'), ('IVYES', 'IVYES')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(choices=[('Payment mode 1', 'Payment mode 1'), ('Payment mode 2', 'Payment mode 2'), ('Payment mode 3', 'Payment mode 3'), ('Payment mode 4', 'Payment mode 4'), ('Payment mode 5', 'Payment mode 5')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dm_page.tag'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='type_of_donation',
            field=models.CharField(choices=[('Donation Type 1', 'Donation Type 1'), ('Donation Type 2', 'Donation Type 2'), ('Donation Type 3', 'Donation Type 3'), ('Donation Type 4', 'Donation Type 4'), ('Donation Type 5', 'Donation Type 5')], max_length=200, null=True),
        ),
    ]
