# Generated by Django 3.1.7 on 2021-05-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0006_auto_20210525_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.contact'),
        ),
    ]
