# Generated by Django 3.1.7 on 2021-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0007_auto_20210525_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
