# Generated by Django 3.1.7 on 2021-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0008_auto_20210525_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
