# Generated by Django 3.1.7 on 2021-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0009_auto_20210525_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='tags',
        ),
        migrations.AddField(
            model_name='donation',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='donations', to='dm_page.Tag'),
        ),
    ]
