# Generated by Django 3.1.7 on 2021-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0010_auto_20210527_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(related_name='contacts', to='dm_page.Tag'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tags',
            field=models.ManyToManyField(related_name='donations', to='dm_page.Tag'),
        ),
    ]
