# Generated by Django 3.1.7 on 2021-05-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0011_auto_20210527_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='tags',
        ),
        migrations.AddField(
            model_name='donation',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.tag'),
        ),
    ]
