# Generated by Django 3.1.7 on 2021-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0012_auto_20210527_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date_donated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
