# Generated by Django 3.1.7 on 2021-05-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0013_auto_20210528_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.tag'),
        ),
    ]
