# Generated by Django 3.1.7 on 2021-05-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0015_auto_20210528_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='tags',
        ),
    ]
