# Generated by Django 3.1.7 on 2021-05-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0016_remove_donation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtype',
            name='donation_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
