# Generated by Django 3.1.7 on 2021-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0019_auto_20210603_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(to='dm_page.Tag'),
        ),
    ]
