# Generated by Django 3.1.7 on 2021-07-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0021_donation_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
    ]
