# Generated by Django 3.1.7 on 2021-08-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0026_auto_20210825_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminar_desk_id', models.PositiveIntegerField(default=None, null=True)),
                ('salutation', models.CharField(default=None, max_length=200, null=True)),
                ('object_type', models.CharField(default=None, max_length=200, null=True)),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('language', models.CharField(default=None, max_length=200, null=True)),
                ('labels', models.TextField(default=None, null=True)),
                ('email', models.CharField(default=None, max_length=200, null=True)),
                ('alternative_email', models.CharField(default=None, max_length=200, null=True)),
                ('website', models.CharField(default=None, max_length=200, null=True)),
                ('fax_number', models.CharField(default=None, max_length=200, null=True)),
                ('primary_address', models.TextField(default=None, null=True)),
                ('billing_address_active', models.CharField(default=None, max_length=200, null=True)),
                ('billing_address', models.TextField(default=None, null=True)),
                ('remarks', models.TextField(default=None, null=True)),
                ('information', models.TextField(default=None, null=True)),
                ('is_blocked', models.CharField(default=None, max_length=200, null=True)),
                ('blocked_reason', models.CharField(default=None, max_length=200, null=True)),
                ('bank_account_data', models.TextField(default=None, null=True)),
                ('tax_number', models.CharField(default=None, max_length=200, null=True)),
                ('vat_id', models.CharField(default=None, max_length=200, null=True)),
                ('customer_number', models.CharField(default=None, max_length=200, null=True)),
                ('additional_fields', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='details',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='organisation',
        ),
        migrations.AddField(
            model_name='contact',
            name='additional_title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='alternative_phone_number',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_subscribed_to_newsletter',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_email',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_phone_number',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='private_phone_number',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='profession',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='salutation_type',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_phone_number',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='additional_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhooklogs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dm_page.profile'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dm_page.profile'),
        ),
    ]
