# Generated by Django 3.1.7 on 2021-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0027_auto_20210825_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_facilitator',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
