# Generated by Django 3.1.7 on 2021-08-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0029_auto_20210827_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dm_page.profile'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dm_page.profile'),
        ),
    ]
