# Generated by Django 3.1.7 on 2021-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0030_auto_20210830_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='pdf_path',
        ),
        migrations.AddField(
            model_name='donation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
