# Generated by Django 3.1.7 on 2021-09-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0031_auto_20210906_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='pdf',
            new_name='pdf_receipt',
        ),
    ]
