# Generated by Django 3.1.7 on 2021-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0033_remove_donation_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pdf_receipt',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
