# Generated by Django 3.1.7 on 2021-09-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0034_auto_20210906_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReceipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(null=True)),
                ('receipt_type', models.CharField(choices=[('A', 'Annual'), ('I', 'Individual')], max_length=200)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.contact')),
            ],
        ),
    ]
