# Generated by Django 3.1.7 on 2021-09-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0035_donationreceipts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonationReceipts',
            new_name='DonationReceipt',
        ),
    ]
