# Generated by Django 3.1.7 on 2021-09-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0041_auto_20210909_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.DateField()),
                ('release_date', models.DateField()),
                ('automatic', models.BooleanField(default=False)),
                ('manual', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='AutomaticReceiptTrigger',
        ),
    ]
