# Generated by Django 3.1.7 on 2021-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0043_auto_20210909_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptsettings',
            old_name='date_range',
            new_name='date_range_end',
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='date_range_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
