# Generated by Django 3.1.7 on 2021-09-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0045_auto_20210909_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paramètres',
            new_name='Paramètre',
        ),
        migrations.RenameModel(
            old_name='RecettesFiscales',
            new_name='RecettesFiscale',
        ),
    ]
