# Generated by Django 3.1.7 on 2021-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0046_auto_20210909_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='automatic',
            field=models.BooleanField(default=False, verbose_name='Automatique'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='date_range_end',
            field=models.DateField(blank=True, null=True, verbose_name='Année Fiscale: Date de fin'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='date_range_start',
            field=models.DateField(blank=True, null=True, verbose_name='Année Fiscale: Date de début'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='manual',
            field=models.URLField(blank=True, null=True, verbose_name='Manuel'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Libération'),
        ),
    ]
