# Generated by Django 3.1.7 on 2021-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0047_auto_20210909_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='date_range_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='date_range_start',
            field=models.DateField(blank=True, help_text="période de l'année fiscale", null=True, verbose_name='Date de début'),
        ),
    ]
