# Generated by Django 3.1.7 on 2021-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0048_auto_20210909_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='date_range_start',
            field=models.DateField(blank=True, null=True, verbose_name='Année Fiscale: Date de début'),
        ),
    ]
