# Generated by Django 3.1.7 on 2021-09-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0049_auto_20210909_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramètre',
            name='donation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.organisation', verbose_name="Conditions d'éligibilité des reçus: Organisation"),
        ),
    ]
