# Generated by Django 3.1.7 on 2021-09-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0050_auto_20210909_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='date_range_start',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.organisation', verbose_name='Organisation'),
        ),
    ]
