# Generated by Django 3.1.7 on 2021-09-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0051_auto_20210909_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation',
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type1', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type2', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type3', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type4', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type5', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation1', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation2', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation3', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation4', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation5', to='dm_page.organisation', verbose_name='Organisation'),
        ),
    ]
