# Generated by Django 3.1.7 on 2021-09-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0052_auto_20210909_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='eligible',
            field=models.BooleanField(default=False),
        ),
    ]
