# Generated by Django 3.1.7 on 2021-09-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0053_donation_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettesfiscale',
            name='referred_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recettesfiscale',
            name='referred_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
