# Generated by Django 3.1.7 on 2021-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0054_auto_20210910_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recettesfiscale',
            name='referred_id',
        ),
        migrations.RemoveField(
            model_name='recettesfiscale',
            name='referred_name',
        ),
        migrations.AddField(
            model_name='recettesfiscale',
            name='donation_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
