# Generated by Django 3.1.7 on 2021-09-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0055_auto_20210910_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
