# Generated by Django 3.1.7 on 2021-09-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0056_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='recettesfiscale',
            name='email_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recettesfiscale',
            name='email_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
