# Generated by Django 3.1.7 on 2021-09-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0057_auto_20210912_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReçusFiscaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('receipt_type', models.CharField(choices=[('A', 'Annual'), ('I', 'Individual')], max_length=200)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('donation_list', models.TextField(blank=True, null=True)),
                ('cancel', models.BooleanField(default=False)),
                ('email_active', models.BooleanField(default=False)),
                ('email_cancel', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disabled',
        ),
        migrations.AddField(
            model_name='donation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='RecettesFiscale',
        ),
    ]
