# Generated by Django 3.1.7 on 2021-09-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0058_auto_20210914_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reçusfiscaux',
            options={'verbose_name_plural': 'reçusfiscaux'},
        ),
    ]
