# Generated by Django 3.1.7 on 2021-09-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0059_auto_20210915_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reçusfiscaux',
            options={},
        ),
    ]
