# Generated by Django 3.1.7 on 2021-09-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0060_auto_20210915_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reçusfiscaux',
            options={'verbose_name': 'reçusfiscaux', 'verbose_name_plural': 'reçusfiscaux'},
        ),
    ]
