# Generated by Django 3.1.7 on 2021-09-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0061_auto_20210915_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reçusfiscaux',
            options={'verbose_name': 'Reçus Fiscaux', 'verbose_name_plural': 'Reçus Fiscaux'},
        ),
    ]
