# Generated by Django 3.1.7 on 2021-09-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0062_auto_20210915_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reçusfiscaux',
            options={'verbose_name': 'Bob the builder', 'verbose_name_plural': 'Bob the builders'},
        ),
    ]
