# Generated by Django 3.1.7 on 2021-09-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0063_auto_20210916_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reçusfiscaux',
            options={'verbose_name': 'Reçus Fiscaux', 'verbose_name_plural': 'Reçus Fiscaux'},
        ),
    ]
