# Generated by Django 3.1.7 on 2021-09-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0064_auto_20210916_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormeDuDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('default', models.BooleanField(default=False, verbose_name='Valeur par Défaut')),
            ],
        ),
        migrations.CreateModel(
            name='NatureDuDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('default', models.BooleanField(default=False, verbose_name='Valeur par Défaut')),
            ],
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='forme_du_don_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='nature_du_don_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_mode_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='additional_name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='forme_du_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.formedudon'),
        ),
        migrations.AddField(
            model_name='donation',
            name='nature_du_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dm_page.naturedudon'),
        ),
    ]
