# Generated by Django 3.1.7 on 2021-09-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0065_auto_20210916_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationtype',
            options={'verbose_name': 'Type de Don', 'verbose_name_plural': 'Types de Dons'},
        ),
        migrations.AlterModelOptions(
            name='formedudon',
            options={'verbose_name': 'Forme du Don', 'verbose_name_plural': 'Forme des Dons'},
        ),
        migrations.AlterModelOptions(
            name='naturedudon',
            options={'verbose_name': 'Nature du Don', 'verbose_name_plural': 'Nature des Dons'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
    ]
