# Generated by Django 3.1.7 on 2021-09-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0066_auto_20210916_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='additional_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
