# Generated by Django 3.1.7 on 2021-09-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0067_auto_20210916_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type10', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type6', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type7', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type8', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='donation_type_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_type9', to='dm_page.donationtype', verbose_name='Type de don'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='institut_post_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='institut_street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='institut_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='institut_town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='object_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='object_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation10', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation6', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation7', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation8', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='organisation_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation9', to='dm_page.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='president',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='president_signature',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
