# Generated by Django 3.1.7 on 2021-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0068_auto_20210916_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Image de l'Institut"),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='institut_post_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='institut_street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='institut_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='institut_town',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='object_description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'Objet"),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='object_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Titre de l'Objet"),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='president',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Président'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='president_signature',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Signature du Président'),
        ),
    ]
