# Generated by Django 3.1.7 on 2021-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0069_auto_20210916_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramètre',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='cc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='host_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hôte Email'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='host_password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='smtp_domain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SMTP Domain'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='smtp_port',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SMTP Port'),
        ),
    ]
