# Generated by Django 3.1.7 on 2021-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0070_auto_20210916_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='manual',
            field=models.URLField(blank=True, null=True, verbose_name='Lien'),
        ),
    ]
