# Generated by Django 3.1.7 on 2021-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0071_auto_20210916_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien'),
        ),
    ]
