# Generated by Django 3.1.7 on 2021-09-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0074_auto_20210916_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='reçusfiscaux',
            name='cancel_description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'annulation"),
        ),
        migrations.AlterField(
            model_name='reçusfiscaux',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='Annuler'),
        ),
    ]
