# Generated by Django 3.1.7 on 2021-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0075_auto_20210916_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date_donated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Locked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('contacts', models.ManyToManyField(blank=True, null=True, to='dm_page.Contact', verbose_name='Contacts')),
                ('donation_types', models.ManyToManyField(blank=True, null=True, to='dm_page.DonationType', verbose_name='Type de dons')),
                ('organisations', models.ManyToManyField(blank=True, null=True, to='dm_page.Organisation', verbose_name='Organisations')),
            ],
        ),
    ]
