# Generated by Django 3.1.7 on 2021-09-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0076_auto_20210917_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locked',
            options={'verbose_name': 'Verouillement', 'verbose_name_plural': 'Verouillement'},
        ),
    ]
