# Generated by Django 3.1.7 on 2021-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0078_auto_20210917_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='locked',
            name='donation_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
