# Generated by Django 3.1.7 on 2021-09-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0079_locked_donation_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locked',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='locked',
            name='donation_types',
        ),
        migrations.RemoveField(
            model_name='locked',
            name='organisations',
        ),
    ]
