# Generated by Django 3.1.7 on 2021-09-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0080_auto_20210917_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='locked',
            name='contacts',
            field=models.ManyToManyField(to='dm_page.Contact', verbose_name='Contacts'),
        ),
        migrations.AddField(
            model_name='locked',
            name='donation_types',
            field=models.ManyToManyField(to='dm_page.DonationType', verbose_name='Types des Dons'),
        ),
        migrations.AddField(
            model_name='locked',
            name='organisations',
            field=models.ManyToManyField(to='dm_page.Organisation', verbose_name='Organisations'),
        ),
    ]
