# Generated by Django 3.1.7 on 2021-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0081_auto_20210917_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='locked',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=200, verbose_name='Nom'),
            preserve_default=200,
        ),
    ]
