# Generated by Django 3.1.7 on 2021-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0082_locked_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramètre',
            name='release_notification',
            field=models.BooleanField(default=False),
        ),
    ]
