# Generated by Django 3.1.7 on 2021-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0083_paramètre_release_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramètre',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='email_notification_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
