# Generated by Django 3.1.7 on 2021-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0084_auto_20210921_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='locked',
            options={'verbose_name': 'Verouillage', 'verbose_name_plural': 'Verouillage'},
        ),
    ]
