# Generated by Django 3.1.7 on 2021-10-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0086_auto_20211019_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='additional_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='institut_image',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='institut_post_code',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='institut_street_name',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='institut_title',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='institut_town',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='object_description',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='object_title',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='president',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='president_signature',
        ),
        migrations.AddField(
            model_name='organisation',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Image de l'Institut"),
        ),
        migrations.AddField(
            model_name='organisation',
            name='institut_post_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='institut_street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rue'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='institut_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='institut_town',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='object_description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'Objet"),
        ),
        migrations.AddField(
            model_name='organisation',
            name='object_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Titre de l'Objet"),
        ),
        migrations.AddField(
            model_name='organisation',
            name='president',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Président'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='president_signature',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Signature du Président'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='used_for_receipt',
            field=models.BooleanField(default=False),
        ),
    ]
