# Generated by Django 3.1.7 on 2021-10-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0087_auto_20211019_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmode',
            options={'verbose_name': 'Mode de Paiement', 'verbose_name_plural': 'Mode de Paiement'},
        ),
        migrations.AddField(
            model_name='reçusfiscaux',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='pdf/receipts/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='used_for_receipt',
            field=models.BooleanField(default=False, verbose_name='Détails utilisés pour le reçu'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
    ]
