# Generated by Django 3.1.7 on 2021-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0088_auto_20211022_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
