# Generated by Django 3.1.7 on 2021-10-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0089_profile_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf/receipts')),
            ],
        ),
        migrations.RemoveField(
            model_name='reçusfiscaux',
            name='upload',
        ),
    ]
