# Generated by Django 3.2.3 on 2021-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0091_auto_20211027_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Image de l'Institut"),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='president_signature',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Signature du Président'),
        ),
    ]
