# Generated by Django 3.2.3 on 2021-10-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0092_auto_20211027_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to='organisation/', verbose_name="Image de l'Institut"),
        ),
    ]
