# Generated by Django 3.2.3 on 2021-10-27 21:25

from django.db import migrations, models
import dm_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0094_alter_organisation_institut_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to=dm_page.models.path_to_institut_image, verbose_name="Image de l'Institut"),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='president_signature',
            field=models.FileField(blank=True, null=True, upload_to=dm_page.models.path_to_president_signature, verbose_name='Signature du Président'),
        ),
    ]
