# Generated by Django 3.1.7 on 2021-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0096_auto_20211028_0718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFileTest',
        ),
        migrations.AddField(
            model_name='paramètre',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='body',
            field=models.TextField(blank=True, help_text="Écrivez 'R_ID' dans le message pour remplacer l'identifiant actuel du reçu", max_length=200, null=True, verbose_name='Message'),
        ),
    ]
