# Generated by Django 3.1.7 on 2021-10-30 08:17

from django.db import migrations, models
import dm_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0097_auto_20211029_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationtype',
            options={'verbose_name': 'Type de don', 'verbose_name_plural': 'Types de dons'},
        ),
        migrations.AlterModelOptions(
            name='formedudon',
            options={'verbose_name': 'Forme du don', 'verbose_name_plural': 'Forme des dons'},
        ),
        migrations.AlterModelOptions(
            name='locked',
            options={'verbose_name': 'Verrouillage', 'verbose_name_plural': 'Verrouillage'},
        ),
        migrations.AlterModelOptions(
            name='naturedudon',
            options={'verbose_name': 'Nature du don', 'verbose_name_plural': 'Nature des dons'},
        ),
        migrations.AlterModelOptions(
            name='paramètre',
            options={'verbose_name': 'Paramètres généraux', 'verbose_name_plural': 'Paramètres généraux'},
        ),
        migrations.AlterModelOptions(
            name='paymentmode',
            options={'verbose_name': 'Mode de paiement', 'verbose_name_plural': 'Mode de paiement'},
        ),
        migrations.AlterModelOptions(
            name='reçusfiscaux',
            options={'verbose_name': 'Reçus fiscaux', 'verbose_name_plural': 'Reçus fiscaux'},
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='automatic',
        ),
        migrations.AddField(
            model_name='organisation',
            name='president_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonction du signataire'),
        ),
        migrations.AddField(
            model_name='paramètre',
            name='host_email_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='formedudon',
            name='default_value',
            field=models.BooleanField(default=False, verbose_name='Valeur par défaut'),
        ),
        migrations.AlterField(
            model_name='naturedudon',
            name='default_value',
            field=models.BooleanField(default=False, verbose_name='Valeur par défaut'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to=dm_page.models.path_to_institut_image, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='institut_post_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='institut_street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='institut_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nom sur le reçu'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='institut_town',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom interne'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='object_description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'objet"),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='object_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='president',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Signataire'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='president_signature',
            field=models.FileField(blank=True, null=True, upload_to=dm_page.models.path_to_president_signature, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='used_for_receipt',
            field=models.BooleanField(default=False, verbose_name='Utiliser cette organisation pour les reçus fiscaux'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='host_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Adresse de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de notification'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='smtp_domain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SMTP Domaine'),
        ),
    ]
