# Generated by Django 3.1.7 on 2021-11-06 21:16

from django.db import migrations, models
import dm_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0101_auto_20211103_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='institut_image',
            field=models.FileField(blank=True, null=True, upload_to=dm_page.models.path_to_institut_image, validators=[dm_page.models.validate_image], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='president_signature',
            field=models.FileField(blank=True, null=True, upload_to=dm_page.models.path_to_president_signature, validators=[dm_page.models.validate_image], verbose_name='Signature'),
        ),
    ]
