# Generated by Django 3.1.7 on 2021-11-08 11:27

from django.db import migrations, models
import dm_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0102_auto_20211106_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='reçusfiscaux',
            name='email_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='institut_image',
            field=models.FileField(blank=True, help_text='Cette image doit être dans le format .png', null=True, upload_to=dm_page.models.path_to_institut_image, validators=[dm_page.models.validate_image], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='president_signature',
            field=models.FileField(blank=True, help_text='Cette image doit être dans le format .png', null=True, upload_to=dm_page.models.path_to_president_signature, validators=[dm_page.models.validate_image], verbose_name='Signature'),
        ),
    ]
