# Generated by Django 3.1.7 on 2021-11-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0103_auto_20211108_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramètre',
            name='bcc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
