# Generated by Django 3.1.7 on 2021-11-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0106_auto_20211117_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramètre',
            name='body',
            field=models.TextField(blank=True, help_text="Écrivez 'R_ID' dans le message pour remplacer l'identifiant actuel du reçu<br>Écrivez 'AAAA' dans le message pour rajouter l'année actuelle", max_length=10000, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='paramètre',
            name='email_subject',
            field=models.CharField(blank=True, help_text="Écrivez 'R_ID' dans le message pour rajouter l'identifiant actuel du reçu<br>Écrivez 'AAAA' dans le message pour rajouter l'année actuelle", max_length=200, null=True, verbose_name='Sujet'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='contact',
            order_with_respect_to='profile',
        ),
    ]
