# Generated by Django 3.1.7 on 2021-12-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0107_auto_20211124_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='used_for_receipt',
        ),
    ]
