# Generated by Django 3.1.7 on 2021-12-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_page', '0108_remove_organisation_used_for_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_1',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_10',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_2',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_3',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_4',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_5',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_6',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_7',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_8',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='donation_type_9',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_1',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_10',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_2',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_3',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_4',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_5',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_6',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_7',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_8',
        ),
        migrations.RemoveField(
            model_name='paramètre',
            name='organisation_9',
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_type', to='dm_page.donationtype', verbose_name='Type de don')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='dm_page.organisation', verbose_name='Organisation')),
            ],
        ),
    ]
